project_id = "ybvlxzpioteopcemkngp"

[functions.gala-login]
verify_jwt = false

[functions.gala-request]
verify_jwt = false

[functions.gala-salary]
verify_jwt = false

[functions.gala-transactions]
verify_jwt = false
