project_id = "ybvlxzpioteopcemkngp"

[functions.gala-login]
verify_jwt = false

[functions.gala-request]
verify_jwt = false

[functions.gala-salary]
verify_jwt = false

[functions.gala-transactions]
verify_jwt = false

[functions.admin-manage]
verify_jwt = false

[functions.admin-upload-video]
verify_jwt = false

[functions.gala-actions]
verify_jwt = false

[functions.bd-referral]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.bd-sync]
verify_jwt = false

[functions.ban-report]
verify_jwt = false

[functions.bd-manage]
verify_jwt = false

[functions.quick-support]
verify_jwt = false

[functions.secure-upload]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.test-user-info]
verify_jwt = false

[functions.extract-svga-name]
verify_jwt = false

[functions.wares-request]
verify_jwt = false

[functions.ban-check]
verify_jwt = false
