project_id = "ybvlxzpioteopcemkngp"

[functions.gala-login]
verify_jwt = false

[functions.gala-request]
verify_jwt = false

[functions.gala-salary]
verify_jwt = false

[functions.gala-transactions]
verify_jwt = false

[functions.admin-manage]
verify_jwt = false

[functions.admin-upload-video]
verify_jwt = false

[functions.gala-actions]
verify_jwt = false

[functions.bd-referral]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false
